# Generated by Django 4.0 on 2021-12-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('pronouns', models.CharField(blank=True, choices=[('HH', 'He/Him/His'), ('SS', 'She/Her/Hers'), ('TT', 'They/Them/Theirs'), ('HT', 'He/They'), ('ST', 'She/They'), ('AM', 'Please Ask For My Pronouns')], default='AM', max_length=4)),
                ('dob', models.DateField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=300)),
                ('refresh_token', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
