# Generated by Django 4.0 on 2021-12-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmatch', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
