# Generated by Django 4.0 on 2021-12-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicmatch', '0002_userprofile_user_alter_userprofile_dob'),
        ('musicmatch', '0005_alter_userprofile_email'),
    ]

    operations = [
    ]
