# Generated by Django 4.0 on 2021-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicmatch', '0007_alter_userprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='musicmatch.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='musicmatch.UserProfile'),
        ),
    ]
